/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 30 12:18:06 GMT 2024
 */

package org.jfree.chart.plot;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.plot.PieLabelDistributor;
import org.jfree.chart.plot.PieLabelRecord;
import org.jfree.chart.text.TextBlock;
import org.jfree.chart.text.TextBox;
import org.jfree.data.general.DefaultKeyedValuesDataset;
import org.jfree.data.time.Second;
import org.jfree.data.time.Week;
import org.jfree.data.time.Year;
import org.jfree.data.xy.XYDatasetTableModel;
import org.junit.runner.RunWith;

public class PieLabelDistributor_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(1397);
      Year year0 = new Year();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord(year0, 3550.9577517, (-332.23), (TextBox) null, (-332.23), 1.5, 0.0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord(year0, 1579.93998, 0.0, (TextBox) null, 3550.9577517, 1579.93998, 3550.9577517);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.distributeLabels((-9999), (-1056.496939552915));
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", 2655.54204, (-1678.382), textBox0, 0.0, 3098.903, 3098.903);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.distributeLabels(0.0, 0.0);
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", (-1678.382), (-1614.728204846371), textBox0, (-1607.6460630851), 858, (-1614.728204846371));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord("", 2655.54204, (-1678.382), textBox0, 0.0, 3098.903, 3098.903);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.distributeLabels(0.0, 0.0);
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", (-1678.382), (-1614.728204846371), textBox0, (-1607.6460630851), 858, (-1614.728204846371));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.distributeLabels(0.0, 0.0);
      assertEquals(3, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-1497283820));
      pieLabelDistributor0.adjustUpwards(0L, 0.0);
      assertEquals(0, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", (-1678.382), (-1614.728204846371), textBox0, (-1607.6460630851), 858, (-1614.728204846371));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord("", 2655.54204, (-1678.382), textBox0, 0.0, 3098.903, 3098.903);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.spreadEvenly((-188.518780081), (-1676.398854932996));
      pieLabelDistributor0.adjustDownwards(0.0, 1502.02204781);
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(0);
      pieLabelDistributor0.adjustDownwards(0.0, 0);
      assertEquals(0, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBlock textBlock0 = new TextBlock();
      TextBox textBox0 = new TextBox(textBlock0);
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", 272.39802799429, (-1614.728204846371), textBox0, 858, 858, (-1675.040650845302));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord("", 2655.54204, (-1678.382), textBox0, 0.0, 3098.903, 3098.903);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.adjustInwards();
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-2073));
      Second second0 = new Second();
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord(second0, (-3215.2921261702), 2.0, textBox0, 2.0, (-854.424), (-854.424));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord(second0, (-2073), 0, textBox0, 59, (-2073), 0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.adjustInwards();
      assertEquals(3, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", (-1678.382), (-1614.728204846371), textBox0, (-1607.6460630851), 858, (-1614.728204846371));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord("", 2655.54204, (-1678.382), textBox0, 0.0, 3098.903, 3098.903);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.adjustInwards();
      assertEquals(3, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(858);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", (-1678.382), (-1614.728204846371), textBox0, (-1607.6460630851), 858, (-1614.728204846371));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      PieLabelRecord pieLabelRecord1 = new PieLabelRecord("", 2655.54204, (-1678.382), textBox0, 0.0, 3098.903, 3098.903);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord1);
      pieLabelDistributor0.spreadEvenly(858, 0.0);
      pieLabelDistributor0.distributeLabels(1402.0, 4363.723662951924);
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(0);
      Week week0 = new Week();
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord(week0, 0.0, 0.0, textBox0, 467.316344, 2.0, 2.0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.distributeLabels(0, (-111.295));
      assertEquals(1, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(0);
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.plot.PieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(2874);
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      pieLabelDistributor0.labels = (List) arrayList0;
      arrayList0.add((Object) pieLabelDistributor0.labels);
      // Undeclared exception!
      try { 
        pieLabelDistributor0.toString();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-1497283820));
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.spreadEvenly(Double.NEGATIVE_INFINITY, 0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.plot.PieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(17);
      Vector<Object> vector0 = new Vector<Object>();
      vector0.add((Object) pieLabelDistributor0);
      pieLabelDistributor0.labels = (List) vector0;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.spreadEvenly(0.0, 1138.13579);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jfree.chart.plot.PieLabelDistributor cannot be cast to org.jfree.chart.plot.PieLabelRecord
         //
         verifyException("org.jfree.chart.plot.AbstractPieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(1);
      DefaultKeyedValuesDataset defaultKeyedValuesDataset0 = new DefaultKeyedValuesDataset();
      List list0 = defaultKeyedValuesDataset0.getKeys();
      pieLabelDistributor0.labels = list0;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.sort();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Collections$UnmodifiableList", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-1643));
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.sort();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-162));
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      pieLabelDistributor0.labels = (List) linkedList0;
      linkedList0.add((Object) "");
      XYDatasetTableModel xYDatasetTableModel0 = new XYDatasetTableModel();
      linkedList0.add((Object) xYDatasetTableModel0);
      // Undeclared exception!
      try { 
        pieLabelDistributor0.sort();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jfree.data.xy.XYDatasetTableModel cannot be cast to java.lang.Comparable
         //
         verifyException("java.util.ComparableTimSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(0);
      DefaultKeyedValuesDataset defaultKeyedValuesDataset0 = new DefaultKeyedValuesDataset();
      List list0 = defaultKeyedValuesDataset0.getKeys();
      pieLabelDistributor0.labels = list0;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.distributeLabels(0, 0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Collections$UnmodifiableList", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(0);
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.distributeLabels(0, 91.49845);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(0);
      LinkedList<XYDatasetTableModel> linkedList0 = new LinkedList<XYDatasetTableModel>();
      XYDatasetTableModel xYDatasetTableModel0 = new XYDatasetTableModel();
      linkedList0.add(xYDatasetTableModel0);
      pieLabelDistributor0.labels = (List) linkedList0;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.distributeLabels(0.0, (-1171.784182838));
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jfree.data.xy.XYDatasetTableModel cannot be cast to org.jfree.chart.plot.PieLabelRecord
         //
         verifyException("org.jfree.chart.plot.AbstractPieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(2729);
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.adjustUpwards(2546.635209696747, (-2951.4));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.plot.PieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(2080);
      Stack<String> stack0 = new Stack<String>();
      pieLabelDistributor0.labels = (List) stack0;
      stack0.add(">-,.6");
      stack0.add(">;&n<iG@^{Tu\"A");
      // Undeclared exception!
      try { 
        pieLabelDistributor0.adjustUpwards(2218.38820044222, 4664.721965022535);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to org.jfree.chart.plot.PieLabelRecord
         //
         verifyException("org.jfree.chart.plot.AbstractPieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(919);
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.adjustInwards();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.plot.PieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(996);
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      TextStyle textStyle0 = TextStyle.NARROW_STANDALONE;
      vector0.add(textStyle0);
      pieLabelDistributor0.labels = (List) vector0;
      vector0.add(textStyle0);
      // Undeclared exception!
      try { 
        pieLabelDistributor0.adjustInwards();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.time.format.TextStyle cannot be cast to org.jfree.chart.plot.PieLabelRecord
         //
         verifyException("org.jfree.chart.plot.AbstractPieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-1266));
      pieLabelDistributor0.labels = null;
      // Undeclared exception!
      try { 
        pieLabelDistributor0.adjustDownwards(0.0, (-1266));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.plot.PieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(2874);
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      arrayList0.add((Object) pieLabelDistributor0);
      pieLabelDistributor0.labels = (List) arrayList0;
      arrayList0.add((Object) pieLabelDistributor0.labels);
      // Undeclared exception!
      try { 
        pieLabelDistributor0.adjustDownwards(0.0, 2.0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jfree.chart.plot.PieLabelDistributor cannot be cast to org.jfree.chart.plot.PieLabelRecord
         //
         verifyException("org.jfree.chart.plot.AbstractPieLabelDistributor", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-162));
      pieLabelDistributor0.sort();
      assertEquals(0, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-2090));
      Second second0 = new Second();
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord(second0, (-2090), 0, textBox0, 59, (-2090), (-2090));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      String string0 = pieLabelDistributor0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(865);
      String string0 = pieLabelDistributor0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor((-2090));
      Second second0 = new Second();
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord(second0, (-2090), 0, textBox0, 59, (-2090), (-2090));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.spreadEvenly(1.7976931348623157E308, 1.7976931348623157E308);
      pieLabelDistributor0.adjustInwards();
      assertEquals(3, pieLabelDistributor0.getItemCount());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PieLabelDistributor pieLabelDistributor0 = new PieLabelDistributor(865);
      TextBox textBox0 = new TextBox();
      PieLabelRecord pieLabelRecord0 = new PieLabelRecord("", 865, 865, textBox0, (-1608.1614386107406), 865, (-1608.1614386107406));
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.addPieLabelRecord(pieLabelRecord0);
      pieLabelDistributor0.adjustInwards();
      assertEquals(2, pieLabelDistributor0.getItemCount());
  }
}
