/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 26 12:50:21 GMT 2024
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.CharRange;
import org.apache.commons.lang3.CharSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class CharSet_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[1];
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      CharSet charSet1 = CharSet.ASCII_ALPHA_LOWER;
      boolean boolean0 = charSet1.equals(charSet0);
      assertFalse(boolean0);
      assertFalse(charSet0.equals((Object)charSet1));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[2] = "frCJ.yCR4] (^l+@.k";
      CharSet charSet0 = new CharSet(stringArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "A-Za-z";
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      assertNotNull(charSet0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      charSet0.add("G;~]E7{acL");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[0];
      CharSet charSet0 = new CharSet(stringArray0);
      CharRange[] charRangeArray0 = charSet0.getCharRanges();
      assertEquals(0, charRangeArray0.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      boolean boolean0 = charSet0.contains('v');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharSet charSet0 = null;
      try {
        charSet0 = new CharSet((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      boolean boolean0 = charSet0.equals("G;~]E7{acL");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      String[] stringArray0 = new String[1];
      CharSet charSet1 = CharSet.getInstance(stringArray0);
      boolean boolean0 = charSet1.equals(charSet0);
      assertFalse(boolean0);
      assertFalse(charSet0.equals((Object)charSet1));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[4] = "!-Z";
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      assertNotNull(charSet0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[6] = "A&4i^r-;~T";
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      assertNotNull(charSet0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[17];
      stringArray0[8] = "5S7^909S";
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      charSet0.hashCode();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "G;~]E7{acL";
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      assertNotNull(charSet0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[1];
      CharSet charSet0 = CharSet.getInstance(stringArray0);
      boolean boolean0 = charSet0.equals(charSet0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CharSet charSet0 = CharSet.getInstance((String[]) null);
      assertNull(charSet0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      CharRange[] charRangeArray0 = charSet0.ASCII_ALPHA_LOWER.getCharRanges();
      assertEquals(1, charRangeArray0.length);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      boolean boolean0 = charSet0.contains('@');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CharSet charSet0 = CharSet.ASCII_ALPHA;
      String string0 = charSet0.toString();
      assertNotNull(string0);
  }
}
